LSTM - долгая краткосрочная память | #23 нейросети на Python

Как делать сентимент-анализ рекуррентной LSTM сетью | #24 нейросети на Python

In [39]:

import numpy as np
import os
from tensorflow.keras.layers import Dense, SimpleRNN, Input, Embedding,LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.optimizers import Adam

In [40]:
with open('train_data_true', 'r', encoding='utf-8') as f:
    text_true = f.read() 
    text_true = text_true.replace('\ufeff', '')  


In [41]:
with open('train_data_false', 'r', encoding='utf-8') as f:
    text_false = f.read() 
    text_false = text_false.replace('\ufeff', '')  



In [42]:
texts = text_true + text_false
count_true = len(text_true)
count_false = len(text_false)
total_lines = count_true + count_false
print(count_false, count_true, total_lines)


4102 6598 10700


In [43]:
maxWordsCOunt = 10000
tokenizer = Tokenizer(num_words=maxWordsCOunt, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»', lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts(texts)


In [44]:
dist = list(tokenizer.word_counts.items())
print(dist[:10])
print(texts[0][:100])

[('д', 260), ('у', 231), ('м', 281), ('а', 550), ('й', 125), ('т', 696), ('е', 819), ('п', 241), ('о', 931), ('з', 163)]
Д


In [45]:
max_text_len = 10
data = tokenizer.texts_to_sequences(texts)
data_pad = pad_sequences(data, maxlen=max_text_len)
print(data_pad)
print(list(tokenizer.word_index.items()))

[[ 0  0  0 ...  0  0 12]
 [ 0  0  0 ...  0  0 15]
 [ 0  0  0 ...  0  0 11]
 ...
 [ 0  0  0 ...  0  0  4]
 [ 0  0  0 ...  0  0  3]
 [ 0  0  0 ...  0  0 13]]
[('о', 1), ('е', 2), ('т', 3), ('и', 4), ('н', 5), ('а', 6), ('с', 7), ('в', 8), ('л', 9), ('р', 10), ('м', 11), ('д', 12), ('ь', 13), ('п', 14), ('у', 15), ('к', 16), ('ы', 17), ('я', 18), ('б', 19), ('з', 20), ('ч', 21), ('г', 22), ('й', 23), ('ж', 24), ('ш', 25), ('х', 26), ('ю', 27), ('э', 28), ('щ', 29), ('ц', 30), ('ф', 31), ('ъ', 32), ('ё', 33), ('3', 34)]


In [46]:
x = data_pad
y = np.array([[1, 0]]*count_true + [[0,1]]*count_false)
print(x.shape, y.shape)

(10700, 10) (10700, 2)


In [47]:
indeces = np.random.choice(x.shape[0], size=x.shape[0], replace=False)
x = x[indeces]
y = y[indeces]

In [50]:
model = Sequential()
model.add(Embedding(maxWordsCOunt, 128, input_length=max_text_len))
model.add(LSTM(128, return_sequences=True))
model.add(LSTM(64))
model.add(Dense(2, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy', optimizer=Adam(0.0001), metrics=['accuracy'])

history = model.fit(x, y, batch_size=32, epochs=50)

reverse_word_map = dict(map(reversed, tokenizer.word_index.items()))


/Users/apple/python/SkillFactory/Ml_learning/venv/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50


2024-12-31 11:00:43.543009: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


335/335 ━━━━━━━━━━━━━━━━━━━━ 8s 19ms/step - accuracy: 0.6040 - loss: 0.6716
Epoch 2/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 19ms/step - accuracy: 0.6074 - loss: 0.6704
Epoch 3/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 19ms/step - accuracy: 0.6203 - loss: 0.6642
Epoch 4/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.6159 - loss: 0.6656
Epoch 5/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.6127 - loss: 0.6666
Epoch 6/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.6064 - loss: 0.6678
Epoch 7/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.6160 - loss: 0.6611
Epoch 8/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.6214 - loss: 0.6589
Epoch 9/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.6176 - loss: 0.6618
Epoch 10/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.6159 - loss: 0.6614
Epoch 11/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.6256 - loss: 0.6560
Epoch 12/50
335/335 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/ste

In [52]:
def sequence_to_text(list_of_indices):
    words = [reverse_word_map.get(letter) for letter in list_of_indices]
    return(words)

t = 'привет как дела'.lower()
data = tokenizer.texts_to_sequences([t])
data_pad = pad_sequences(data, maxlen=max_text_len)
print(sequence_to_text(data_pad[0]))

res = model.predict(data_pad)
print(res, np.argmax(res), sep='\n')

[None, None, None, None, None, None, None, None, None, None]
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 630ms/step
[[0.6087827  0.39121726]]
0
