9.7. Алгоритмы SVD и ALS

Singular Value Decomposition (SVD)

В теореме о сингулярном разложении утверждается, что у любой матрицы размера × существует разложение в произведение трех матриц  

В теореме о сингулярном разложении утверждается, что у любой матрицы размера × существует разложение в произведение трех матриц  U,\ \Sigma,\ V^{T}:



Матрицы U и V ортогональные, а Ʃ — диагональная

Усеченное разложение — из лямбд остаются только первые чисел, остальные равны нулю.

У нас была матрица, мы разложили ее в произведение трех (двух) матриц, причем разложили приблизительно. 

Теперь чтобы предсказать оценку пользователя для фильма , мы:

берем некоторый вектор (набор параметров) для данного пользователя 
берем вектор для данного фильма . 
Их скалярное произведение и будет нужным нам предсказанием:

https://lms-cdn.skillfactory.ru/assets/courseware/v1/be18250d5b2ade2a476c066aea4bc447/asset-v1:SkillFactory+MLDL+ALWAYS+type@asset+block/ml9_7.png

Алгоритм достаточно простой, но дает удивительно хорошие результаты

Почему сразу не сделать SVD:

матрица оценок нам полностью не известна
SVD-разложение не единственное 
У нас есть оценки пользователей, при помощи которых мы можем найти такие оптимальные параметры, при которых модель предсказывала бы эти оценки как можно лучше:

E_{(u,i)}(\hat{r_{ui}(\Theta )-r_{ui})^{2}\rightarrow \underset{\Theta}{\min}}

Мы хотим найти такие параметры θ, чтобы квадрат ошибки был как можно меньше. 

Парадокс: мы хотим меньше ошибаться в будущем, но мы не знаем, какие оценки у нас будут спрашивать. И оптимизировать это мы не можем. 

Но нам известны уже проставленные пользователями оценки. Попробуем подобрать параметры так, чтобы на тех оценках, которые у нас уже есть, ошибка была как можно меньше:

https://lms-cdn.skillfactory.ru/assets/courseware/v1/ffc459cd618567e6f25e6b06b2f63cf3/asset-v1:SkillFactory+MLDL+ALWAYS+type@asset+block/ml9_8.png

Alternating Least Squares (ALS)

ALS — итеративный алгоритм разложения матрицы предпочтений на произведение 2 матриц: 

факторов пользователей (U) 
факторов товаров (I).
Работает по принципу минимизации среднеквадратичной ошибки на проставленных рейтингах. 

https://lms-cdn.skillfactory.ru/assets/courseware/v1/c562d6f789e6fbf3ad240d855f5a1eb9/asset-v1:SkillFactory+MLDL+ALWAYS+type@asset+block/ml9_9_1.png


Оптимизация происходит поочередно:

сначала по факторам пользователей
потом по факторам товаров.
Для обхода переобучения, к ошибке добавляются регуляризационные коэффициенты.

А если предпочтения меняются?

Матрица предпочтений отражает предпочтения «в плоскости»
Матрица предпочтений не отражает изменения предпочтений во времени
Матрица предпочтений не учитывает близость продуктов по  составу/цели/назначению

In [1]:
import numpy as np
import scipy.linalg

# Матрица пользователь-фильм
user_movie_matrix = np.array([[1, 5, 0, 5, 4],
                              [5, 4, 4, 3, 2],
                              [0, 4, 0, 0, 5],
                              [4, 4, 1, 4, 0],
                              [0, 4, 3, 5, 0],
                              [2, 4, 3, 5, 3]])

In [2]:
# Применение SVD разложения
U, s, Vt = scipy.linalg.svd(user_movie_matrix)

# Преобразование s в диагональную матрицу
Sigma = np.diag(s)


In [3]:
print("U matrix:\n", U)
print("Sigma matrix:\n", Sigma)
print("V^T matrix:\n", Vt)


U matrix:
 [[-0.45995612  0.39643205  0.30008466 -0.43188307  0.32259944 -0.5006374 ]
 [-0.46080622 -0.30693176 -0.6474524   0.28369822  0.01979887 -0.43974907]
 [-0.24879658  0.7546451  -0.27901701  0.15629367 -0.46458544  0.22470694]
 [-0.38343916 -0.34546491 -0.13187024 -0.68331121 -0.32184406  0.38176018]
 [-0.37621687 -0.24437478  0.62120015  0.38026413 -0.50209455 -0.12709231]
 [-0.47500898 -0.00895923  0.09810557  0.31152785  0.56922355  0.58617101]]
Sigma matrix:
 [[16.46644354  0.          0.          0.          0.        ]
 [ 0.          6.21001334  0.          0.          0.        ]
 [ 0.          0.          4.39908461  0.          0.        ]
 [ 0.          0.          0.          2.90336429  0.        ]
 [ 0.          0.          0.          0.          1.58445634]]
V^T matrix:
 [[-0.31869431 -0.61196286 -0.29030808 -0.57523564 -0.32978869]
 [-0.40869555  0.22187036 -0.37571481 -0.25558153  0.75977493]
 [-0.74298347  0.03279947 -0.12815454  0.59719556 -0.27172346]
 [-0.

In [5]:
import numpy as np
import scipy.linalg

# Матрица пользователь-фильм
user_movie_matrix = np.array([[1, 5, 0, 5, 4],
                              [5, 4, 4, 3, 2],
                              [0, 4, 0, 0, 5],
                              [4, 4, 1, 4, 0],
                              [0, 4, 3, 5, 0],
                              [2, 4, 3, 5, 3]])

# Применение SVD разложения
U, s, Vt = scipy.linalg.svd(user_movie_matrix)

# Создание расширенной диагональной матрицы Sigma размером (6, 5)
Sigma = np.zeros((U.shape[0], Vt.shape[0]))  # Создаём нулевую матрицу размером 6x5
np.fill_diagonal(Sigma, s)  # Заполняем диагональ сингулярными числами

# Восстановление исходной матрицы
M_restored = np.dot(U, np.dot(Sigma, Vt))
print("Restored matrix:\n", M_restored)


Restored matrix:
 [[1.00000000e+00 5.00000000e+00 3.10862447e-15 5.00000000e+00
  4.00000000e+00]
 [5.00000000e+00 4.00000000e+00 4.00000000e+00 3.00000000e+00
  2.00000000e+00]
 [8.88178420e-16 4.00000000e+00 3.77475828e-15 2.66453526e-15
  5.00000000e+00]
 [4.00000000e+00 4.00000000e+00 1.00000000e+00 4.00000000e+00
  5.34091226e-16]
 [2.10942375e-15 4.00000000e+00 3.00000000e+00 5.00000000e+00
  3.13562695e-15]
 [2.00000000e+00 4.00000000e+00 3.00000000e+00 5.00000000e+00
  3.00000000e+00]]


In [6]:
import numpy as np
import scipy.linalg

# Матрица пользователь-фильм
user_movie_matrix = np.array([[1, 5, 0, 5, 4],
                              [5, 4, 4, 3, 2],
                              [0, 4, 0, 0, 5],
                              [4, 4, 1, 4, 0],
                              [0, 4, 3, 5, 0],
                              [2, 4, 3, 5, 3]])

# Применение SVD разложения
U, s, Vt = scipy.linalg.svd(user_movie_matrix)

# Сокращение размерности до 2х компонент
U_reduced = U[:, :2]       # Первые две колонки матрицы U
Sigma_reduced = np.diag(s[:2])  # Первые два сингулярных числа
Vt_reduced = Vt[:2, :]     # Первые две строки матрицы Vt

# Выбор 2-й строки из исходной матрицы (пользователь №2)
user_2 = user_movie_matrix[1, :]  # Вектор пользователя №2

# Перевод пользователя №2 в новое представление сниженной размерности
user_2_reduced = np.dot(user_2, Vt_reduced.T)  # Перемножаем на транспонированную сокращённую матрицу фильмов
print("User 2 in reduced space:", user_2_reduced)

# Обратная трансформация в исходное пространство оценок фильмов
user_2_restored = np.dot(user_2_reduced, Vt_reduced)  # Перемножаем обратно на матрицу фильмов
print("Restored user 2 ratings:", user_2_restored)


User 2 in reduced space: [-7.58783957 -1.90605029]
Restored user 2 ratings: [3.19719556 4.22057993 2.91894245 4.851947   1.05421441]


In [7]:
import numpy as np
import scipy.linalg

# Матрица пользователь-фильм
user_movie_matrix = np.array([[1, 5, 0, 5, 4],
                              [5, 4, 4, 3, 2],
                              [0, 4, 0, 0, 5],
                              [4, 4, 1, 4, 0],
                              [0, 4, 3, 5, 0],
                              [2, 4, 3, 5, 3]])

# Применение SVD разложения на 3 компоненты
U, s, Vt = scipy.linalg.svd(user_movie_matrix)

# Сокращение размерности до 3х компонент
U_reduced = U[:, :3]       # Первые три колонки матрицы U
Sigma_reduced = np.diag(s[:3])  # Первые три сингулярных числа
Vt_reduced = Vt[:3, :]     # Первые три строки матрицы Vt

# Новый пользователь (что-то успел посмотреть)
new_user = np.array((0, 0, 3, 4, 0))

# Перевод нового пользователя в представление сниженной размерности
new_user_reduced = np.dot(new_user, Vt_reduced.T)
print("New user in reduced space:", new_user_reduced)

# Обратная трансформация в исходное пространство оценок фильмов
new_user_restored = np.dot(new_user_reduced, Vt_reduced)
print("Restored ratings for new user:", new_user_restored)

# Поиск индекса непросмотренного фильма с наивысшей оценкой
# Фильмы, которые пользователь не смотрел, имеют рейтинг 0 в исходном векторе
unwatched_indices = np.where(new_user == 0)[0]  # Индексы непросмотренных фильмов
best_movie_index = unwatched_indices[np.argmax(new_user_restored[unwatched_indices])]  # Индекс фильма с наивысшей оценкой

print("Index of the best movie for the new user:", best_movie_index)


New user in reduced space: [-3.17186679 -2.14947056  2.00431861]
Restored ratings for new user: [ 0.40015936  1.52990144  1.47154395  3.57090597 -1.13168846]
Index of the best movie for the new user: 1
